version = 1

test_patterns = ["**/*_test.go"]
exclude_patterns = ["**/mocks/"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/danmx/sigil"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]
