---
kind: pipeline
name: default
# Build
steps:
- name: build
  image: golang:1.12
  environment:
    VERSION: DEV
    REVISION: ${DRONE_COMMIT}
  commands:
    - make bootstrap
    - make build build-dev
  when:
    event:
      - push
- name: build-release
  image: golang:1.12
  environment:
    VERSION: ${DRONE_TAG}
    REVISION: ${DRONE_COMMIT}
  commands:
    - make bootstrap
    - make build
  when:
    event:
      - tag
# Docker Hub
- name: docker-release
  image: plugins/docker
  settings:
    repo: danmx/sigil
    target: prod
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event: tag
# GitHub Release
- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - dist/*
    checksum:
      - sha1
      - sha256
      - sha512
  when:
    event: tag
---
kind: signature
hmac: 37f96f5abde3a97fe6fafd29ae486cf5a1c1587089a7f9640d1119fc83ba782b

...
